### ISSUE TITLE
Foutmelding: 

### ISSUE THREAD

**Issue by sananwar** [StanNieuwmans/WindesheimPython#7]
ping to 172.20.10.8 failed!
Traceback (most recent call last):
  File "/home/pi/Downloads/WindesheimPython-master/wifiAddressScanner.py", line 12, in <module>
    functions.checkIfIpStillOnline()
  File "/home/pi/Downloads/WindesheimPython-master/functions.py", line 86, in checkIfIpStillOnline
    scanNetwork()
TypeError: scanNetwork() missing 1 required positional argument: 'networkAdress'

**Comment by StanNieuwmans** [comment]
@sananwar Dit is gefixed in de laaste versie
